Added the target_status field to the bid obj
flash-global/rtech-struct pull request #54
Opened 2022-11-30 12:00 UTC by IvanNoveo

Card: https://sprints.zoho.eu/team/redspherproduct#itemdetails/P20/I702

2022-11-30 12:30 UTC, gbo-redspher requested changes
wait for the enum validation before merging

2022-11-30 12:30 UTC, gbo-redspher commented on structures/bid.js
> -            bid_score_process: s.optional(s.size(s.string(), 2, 254))
Can it only be `approved` ? I've asked @rendakbalazs confirmation

2022-11-30 12:45 UTC, gbo-redspher approved these changes

2022-11-30 12:52 UTC, gbo-redspher commented
@IvanNoveo Add the correct curl to update the solr in the description of this PR and in the one you'll do in shaq also

2022-11-30 12:58 UTC, IvanNoveo commented
@gbo-redspher Done. I've also updated test Solr instance

2022-12-01 09:58 UTC, gbo-redspher approved these changes

2022-12-01 10:45 UTC, merged