Feature/address book v3
flash-global/rtech-struct pull request #69
Opened 2023-04-12 16:31 UTC by gbo-redspher

+ packages update
+ code cleanup
I might have been too far (and still want to improve most of this), but enough time was already spent on it.

2023-04-14 07:55 UTC, redsphertim requested changes

2023-04-14 07:55 UTC, redsphertim commented on definition/address-book/v3/Address.ts
> +};
Probably better to extend `InputAddress`

2023-04-14 07:55 UTC, redsphertim commented on definition/address-book/v3/Address.ts
> +};
Also not really sure about `zip_code` optional. I know that in the BRD it is listed as optional, but in address-book it was required and we have it required in `uploadAddress` logic. 
Might be worth to ask archi about this one, in case they made mistake

2023-04-14 07:55 UTC, redsphertim commented on definition/address-book/v3/UploadJobState.ts
> +  error: string
`error` field should be optional

2023-04-14 07:55 UTC, redsphertim commented on structures/address-book/v3/inputAddress.js
> +  id: defaulted(Uuid, () => uuidV4()),
I suppose you want to let superstruct handle `id` creation on POST requests? Can you confirm?

2023-04-14 15:43 UTC, gbo-redspher commented on structures/address-book/v3/inputAddress.js
> +  id: defaulted(Uuid, () => uuidV4()),
Yup!

2023-04-14 15:50 UTC, gbo-redspher commented on definition/address-book/v3/Address.ts
> +};
I'd rather not, because of the id (which is optional in Input), but also because both will be used in different contexts

2023-04-14 15:53 UTC, gbo-redspher commented on definition/address-book/v3/UploadJobState.ts
> +  error: string
fixed

2023-04-17 06:55 UTC, redsphertim commented on definition/address-book/v3/Address.ts
> +};
After extend you can override field behavior just fine. 
```suggestion
type Address = InputAddress & {
  id: string,
};
```
If `InputAddress` has `id` set as optional, it will be required in `Address`.

About `zip_code`, that's my point in legacy data it was required(you cannot create a record without it), so I was surprised it's not the case here.

2023-04-17 14:10 UTC, redsphertim approved these changes

2023-04-17 14:11 UTC, merged

2023-04-17 14:54 UTC, ivan-kalinichenko commented on structures/filter.js
> +    id: require('uuid').v4()
Are you sure, you want dynamic import here?