Fix date bug
flash-global/rtech-struct pull request #9
Opened 2022-02-23 15:51 UTC by gbo-redspher

2022-02-25 09:51 UTC, fanshan submitted a review, later dismissed
Case structure should be present directly on the Case Service not on rtech-struct

2022-02-25 09:51 UTC, fanshan commented on structures/case-service/error.js
> +const error = s.object({
`Case` here

2022-02-25 09:51 UTC, fanshan commented on structures/case-service/error.js
> +  error_code: s.integer(),
Should be string

2022-02-25 09:51 UTC, fanshan commented on structures/case-service/errorList.js
> +const errorList = s.object({
CaseList

2022-02-25 09:51 UTC, fanshan commented on structures/case-service/errorList.js
> +  errors: s.array(error),
cases

2022-02-25 09:51 UTC, fanshan commented on structures/case-service/errorList.js
> +const s = require('superstruct')
No need to validate the output of the case service

2022-03-01 17:04 UTC, glickel requested changes

2022-03-01 17:04 UTC, glickel commented on structures/lib.js
> +    return false
```suggestion
    new Date(date).toISOString()
    return zdReg.test(date)
```

2022-03-07 15:47 UTC, gbo-redspher commented
@glickel @fanshan What should we do with this one ?

2022-03-07 16:17 UTC, merged